users:
  - name: Aarav
    username: aarav01
    pref1: Technology
    pref2: Finance
    pref3: Sports
  
  - name: Aisha
    username: aisha02
    pref1: Cinema
    pref2: Lifestyle
    pref3: Travel
